---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - install
    - lnd

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'group create lnd'
  group:
    state: 'present'
    name: "{{group_name_lnd}}"
    system: "{{group_system_lnd}}"
  tags:
    - install
    - lnd

- name: 'user create lnd'
  user:
    state: 'present'
    name: "{{user_name_lnd}}"
    comment: "{{user_comment_lnd}}"
    group: "{{user_group_lnd}}"
    append: "{{user_append_lnd}}"
    createhome: "{{user_home_create_lnd}}"
    move_home: "{{user_home_move_lnd}}"
    remove: "{{user_home_remove_lnd}}"
    force: "{{user_home_force_lnd}}"
    password: "{{user_password_lnd}}"
    update_password: "{{user_password_update_lnd}}"
    shell: "{{user_shell_lnd}}"
    system: "{{user_system_lnd}}"
  tags:
    - install
    - lnd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create app.dir'
  file:
    state: 'directory'
    path: "{{file_dst_app_dir}}"
    mode: "{{file_mode_app_dir}}"
    owner: "{{file_owner_app_dir}}"
    group: "{{file_group_app_dir}}"
  tags:
    - install
    - lnd

- name: 'file create lnd_app.dir'
  file:
    state: 'directory'
    path: "{{file_dst_lnd_app_dir}}"
    mode: "{{file_mode_lnd_app_dir}}"
    owner: "{{file_owner_lnd_app_dir}}"
    group: "{{file_group_lnd_app_dir}}"
  tags:
    - install
    - lnd

- name: 'file create data.dir'
  file:
    state: 'directory'
    path: "{{file_dst_data_dir}}"
    mode: "{{file_mode_data_dir}}"
    owner: "{{file_owner_data_dir}}"
    group: "{{file_group_data_dir}}"
  tags:
    - install
    - lnd

- name: 'file create lnd_data.dir'
  file:
    state: 'directory'
    path: "{{file_dst_lnd_data_dir}}"
    mode: "{{file_mode_lnd_data_dir}}"
    owner: "{{file_owner_lnd_data_dir}}"
    group: "{{file_group_lnd_data_dir}}"
  tags:
    - install
    - lnd

- name: 'file create lnd_log.dir'
  file:
    state: 'directory'
    path: "{{file_dst_lnd_log_dir}}"
    mode: "{{file_mode_lnd_log_dir}}"
    owner: "{{file_owner_lnd_log_dir}}"
    group: "{{file_group_lnd_log_dir}}"
  tags:
    - install
    - lnd

- name: 'file create lnd_src.dir'
  file:
    state: 'directory'
    path: "{{file_dst_lnd_src_dir}}"
    mode: "{{file_mode_lnd_src_dir}}"
    owner: "{{file_owner_lnd_src_dir}}"
    group: "{{file_group_lnd_src_dir}}"
  tags:
    - install
    - lnd

- name: 'file download lnd.tar.gz'
  get_url:
    url: "{{file_src_lnd_tar_gz}}"
    dest: "{{file_dst_lnd_tar_gz}}"
    mode: "{{file_mode_lnd_tar_gz}}"
    owner: "{{file_owner_lnd_tar_gz}}"
    group: "{{file_group_lnd_tar_gz}}"
    checksum: "{{lnd_checksum_algorithm}}:{{lnd_checksum}}"
  tags:
    - install
    - lnd

- name: 'file unarchive lnd.tar.gz'
  unarchive:
    src: "{{file_src_lnd}}"
    dest: "{{file_dst_lnd}}"
    owner: "{{file_owner_lnd}}"
    group: "{{file_group_lnd}}"
    creates: "{{file_creates_lnd}}"
    remote_src: 'yes'
  tags:
    - install
    - lnd

- name: 'file create lnd-current.link'
  file:
    state: 'link'
    src: "{{file_src_lnd_current_link}}"
    path: "{{file_dst_lnd_current_link}}"
    owner: "{{file_owner_lnd_current_link}}"
    group: "{{file_group_lnd_current_link}}"
  tags:
    - install
    - lnd

- name: 'file create lnd_conf.dir'
  file:
    state: 'directory'
    path: "{{file_dst_lnd_conf_dir}}"
    mode: "{{file_mode_lnd_conf_dir}}"
    owner: "{{file_owner_lnd_conf_dir}}"
    group: "{{file_group_lnd_conf_dir}}"
  tags:
    - install
    - lnd

- name: 'file create lnd.service'
  template:
    src: "{{file_src_lnd_service}}"
    dest: "{{file_dst_lnd_service}}"
    mode: "{{file_mode_lnd_service}}"
    owner: "{{file_owner_lnd_service}}"
    group: "{{file_group_lnd_service}}"
  notify: 'command systemctl daemon-reload'
  tags:
    - install
    - lnd

#-------------------------------------------------------------------------------
# META
#-------------------------------------------------------------------------------

- name: 'meta flush handlers'
  meta: 'flush_handlers'
  tags:
    - install
    - lnd
