---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command systemctl daemon-reload'
  command: "{{command_cmd_systemctl_daemon_reload}}"

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service reloaded bitcoind'
  service:
    state: 'reloaded'
    name: "{{service_name_bitcoind}}"

- name: 'service restart bitcoind'
  service:
    state: 'restarted'
    name: "{{service_name_bitcoind}}"
