---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command systemctl daemon-reload'
  command: "{{command_cmd_systemctl_daemon_reload}}"

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service reload monit'
  service:
    state: 'reloaded'
    name: "{{service_name_monit}}"
  when: (register_check_service_monit.rc == 0)

- name: 'service reloaded lnd'
  service:
    state: 'reloaded'
    name: "{{service_name_lnd}}"

- name: 'service restart lnd'
  service:
    state: 'restarted'
    name: "{{service_name_lnd}}"
